version: '3.8'

services:
    dev:
        container_name: gazin-teste_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3000:3000
           
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src
            - /usr/src/node_modules
        restart: unless-stopped
    prod:
        container_name: gazin-teste_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
           
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src
            - /usr/src/node_modules
        restart: unless-stopped

networks:
    nesjs-network: